version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=go_gin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always